name: voice_chat_core
description: Core services for voice chat functionality including STT, TTS (FlutterTTS, ElevenLabs), and OpenAI communication.
version: 0.0.1
# repository: https://github.com/your_username/voice_chat_core # Optional: Add repo URL if you publish

environment:
  sdk: '>=3.0.0 <4.0.0' # Broaden SDK constraint slightly
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies migrated from voice_chat_gpt
  http: ^1.3.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  just_audio: ^0.9.46
  path_provider: ^2.1.5
  # Foundation is part of flutter sdk, no explicit dependency needed usually

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Use a common lints version

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This package does not define any specific Flutter resources like assets or fonts.
  # Plugins (like speech_to_text, flutter_tts, etc.) register themselves.

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
